import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de" className="h-screen overflow-hidden">
      <body className="h-full">
        <div className="h-full flex flex-col">
          <header className="fixed top-0 left-0 right-0 z-50">
            <Header />
          </header>

          <main className="mt-[80px] mb-[80px] flex-1 overflow-y-auto ">
            {children}
          </main>

          <footer className="fixed bottom-0 left-0 right-0 z-50">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}

